@startuml
title Android_Start_Activity
participant ActivityManagerService as AMS
participant ActivityStarter
participant ActivityStack
participant ActivityStackSupervisor
participant ActivityStack.H
participant ContextImpl
participant Instrumentation
participant Activity
participant ActivityThread
participant ActivityThread.ApplicationThread

[-> ContextImpl : startActivity
ContextImpl -> Instrumentation : execStartActivity
Instrumentation ---> AMS : startActivity
activate AMS
	AMS -> AMS : startActivityAsUser
	activate AMS
		AMS -> ActivityStarter : startActivityMayWait
		activate ActivityStarter
			ActivityStarter -> ActivityStarter : startActivityLocked
			activate ActivityStarter
				ActivityStarter -> ActivityStarter : startActivityUnchecked
				activate ActivityStarter
					ActivityStarter -> ActivityStarter : resumeTargetStackIfNeeded
					ActivityStarter -> ActivityStackSupervisor : resumeFocusedStackTopActivityLocked
					activate ActivityStackSupervisor
						ActivityStackSupervisor -> ActivityStack : resumeTopActivityUncheckedLocked
						activate ActivityStack
							ActivityStack -> ActivityStack : resumeTopActivityInnerLocked
							activate ActivityStack
							    ActivityStack -> ActivityStackSupervisor : pauseBackStacks
							    activate ActivityStackSupervisor
								ActivityStackSupervisor -> ActivityStack : startPausingLocked
								activate ActivityStack
									ActivityStack -> ActivityStack : mResumedActivity
									ActivityStack -> ActivityStack : mPausingActivity
									ActivityStack --> ActivityThread.ApplicationThread : schedulePauseActivity
								deactivate ActivityStack
								deactivate ActivityStackSupervisor
							deactivate ActivityStack
						deactivate ActivityStack
					deactivate ActivityStackSupervisor
					ActivityStarter -> ActivityStack : startActivityLocked
				deactivate ActivityStarter
				ActivityStarter -> ActivityStarter : postStartActivityUncheckedProcessing
			deactivate ActivityStarter
		deactivate ActivityStarter
	deactivate AMS
deactivate AMS
										ActivityThread.ApplicationThread --> ActivityThread : handlePauseActivity
										activate ActivityThread
											ActivityThread -> ActivityThread : performPauseActivity
											activate ActivityThread
												ActivityThread -> ActivityThread : callCallActivityOnSaveInstanceState
												activate ActivityThread
													ActivityThread -> Instrumentation : callActivityOnSaveInstanceState
												deactivate ActivityThread
												ActivityThread -> ActivityThread : performPauseActivityIfNeeded
												activate ActivityThread
													ActivityThread -> Instrumentation : callActivityOnPause
												deactivate ActivityThread
											deactivate ActivityThread
											ActivityThread ---> AMS : activityPaused
										deactivate ActivityThread
											activate AMS
												AMS -> ActivityStack : activityPausedLocked
												activate ActivityStack
													ActivityStack -> ActivityStack.H : removeMessage(PAUSE_TIMEOUT_MSG)
													ActivityStack -> ActivityStack : completePauseLocked
													note right of ActivityStack : resumeNext : true
													activate ActivityStack
														ActivityStack -> ActivityStackSupervisor : resumeFocusedStackTopActivityLocked
														activate ActivityStackSupervisor
															ActivityStackSupervisor -> ActivityStack : resumeTopActivityUncheckedLocked
															activate ActivityStack
																ActivityStack -> ActivityStack : resumeTopActivityInnerLocked
																activate ActivityStack
																alt
																	ActivityStack ---> ActivityThread.ApplicationThread : scheduleResumeActivity
																	ActivityThread.ApplicationThread ---> ActivityThread :handleResumeActivity
																	activate ActivityThread
																		ActivityThread -> ActivityThread : performResumeActivity
																		activate ActivityThread
																			ActivityThread -> Activity : performResume
																		deactivate ActivityThread
																		ActivityThread -> AMS : activityResumed
																	deactivate ActivityThread
																else bingo! next.app == null || next.app.thread == null
																	ActivityStack -> ActivityStackSupervisor : startSpecificActivityLocked
																	activate ActivityStackSupervisor
																		ActivityStackSupervisor -> ActivityStackSupervisor : realStartActivityLocked
																		note right : ...
																		ActivityStackSupervisor -> AMS : startProcessLocked
																		note right : see Android_Start_Activity_2
																	deactivate ActivityStackSupervisor
																end
																deactivate ActivityStack
															deactivate ActivityStack
															ActivityStack -> ActivityStackSupervisor : ensureActivitiesVisibleLocked
															ActivityStackSupervisor -> ActivityStack : ensureActivitiesVisibleLocked
															ActivityStack -> ActivityStack : makeVisibleAndRestartIfNeeded
															ActivityStack -> ActivityStackSupervisor : startSpecificActivityLocked
														deactivate ActivityStackSupervisor
														ActivityStack -> ActivityStackSupervisor : ensureActivitiesVisibleLocked
														activate ActivityStackSupervisor
														ActivityStack -> ActivityStack : makeVisibleAndRestartIfNeeded
														deactivate ActivityStackSupervisor
													deactivate ActivityStack
												deactivate ActivityStack
											deactivate AMS


									alt
										ActivityStack -> ActivityStack : completePauseLocked
										note right of ActivityStack : resumeNext : false
									else
										ActivityStack ---> ActivityStack.H : handleMessage(PAUSE_TIMEOUT_MSG)
										ActivityStack.H -> ActivityStack : activityPausedLocked
										ActivityStack -> ActivityStack : completePauseLocked
										note right of ActivityStack : resumeNext : true
									end











@enduml